remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Kristen's Project Portfolio
description: These are my personal projects as a backend web dev. Included technologies: Python/Django, C#/ASP.NET Core
